// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB_ic561lFl7k5i27nBAe6kammJrm6HHHA',
    appId: '1:528586385117:web:512b9dd642a8426ce99d34',
    messagingSenderId: '528586385117',
    projectId: 'british-body-admin',
    authDomain: 'british-body-admin.firebaseapp.com',
    storageBucket: 'british-body-admin.firebasestorage.app',
    measurementId: 'G-6E5QEW92RD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC3pBwvcdFu_0KJBWb6UYRRVcwM1n6nQ_E',
    appId: '1:528586385117:android:319b547ffed11fafe99d34',
    messagingSenderId: '528586385117',
    projectId: 'british-body-admin',
    storageBucket: 'british-body-admin.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCDIG95HEhD_Q6ULp9qUWjrkPN1RXvTbjY',
    appId: '1:528586385117:ios:03cdd3dfaba4d6c3e99d34',
    messagingSenderId: '528586385117',
    projectId: 'british-body-admin',
    storageBucket: 'british-body-admin.firebasestorage.app',
    iosBundleId: 'com.britishbody.adminapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCDIG95HEhD_Q6ULp9qUWjrkPN1RXvTbjY',
    appId: '1:528586385117:ios:03cdd3dfaba4d6c3e99d34',
    messagingSenderId: '528586385117',
    projectId: 'british-body-admin',
    storageBucket: 'british-body-admin.firebasestorage.app',
    iosBundleId: 'com.britishbody.adminapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB_ic561lFl7k5i27nBAe6kammJrm6HHHA',
    appId: '1:528586385117:web:12e0de4ed36a2b2fe99d34',
    messagingSenderId: '528586385117',
    projectId: 'british-body-admin',
    authDomain: 'british-body-admin.firebaseapp.com',
    storageBucket: 'british-body-admin.firebasestorage.app',
    measurementId: 'G-TF3ZY056E4',
  );
}
